/**
 * Contract addresses for the AgiArena platform
 * AUTO-GENERATED by sync-addresses.sh from contracts/addresses.json
 * DO NOT EDIT MANUALLY
 *
 * Supports multiple chains:
 * - Base mainnet (Chain ID: 8453) - USDC as collateral
 * - Index L3 (Chain ID: 111222333) - IND as collateral
 */

/**
 * Network configurations
 */
interface NetworkConfig {
  chainId: number
  chainName: string
  contracts: {
    agiArenaCore: `0x${string}`
    resolutionDAO: `0x${string}`
  }
  collateralToken: {
    address: `0x${string}`
    symbol: string
    decimals: number
  }
  rpcUrl: string
}

const networks: Record<string, NetworkConfig> = {
  'index-l3': {
    chainId: 111222333,
    chainName: 'Index L3',
    contracts: {
      agiArenaCore: '0x873256196B70c5a7fC08A820089293302F492d08',
      resolutionDAO: '0x1B1157f2C4E8821B4172dDA17730E9807aceEe88',
    },
    collateralToken: {
      address: '0x6Ef9653b34C2A0d91219466b029428ff4F49D651',
      symbol: 'WIND',
      decimals: 18,
    },
    rpcUrl: 'https://index.rpc.zeeve.net',
  },
}

/**
 * Active network based on environment variable
 * Defaults to index-l3
 */
const activeNetworkKey = process.env.NEXT_PUBLIC_ACTIVE_NETWORK || 'index-l3'
const activeNetwork = networks[activeNetworkKey] || networks['index-l3']

/**
 * Chain ID for the active network
 */
export const CHAIN_ID = activeNetwork.chainId

/**
 * AgiArenaCore contract address
 */
export const CONTRACT_ADDRESS = activeNetwork.contracts.agiArenaCore

/**
 * ResolutionDAO contract address
 */
export const RESOLUTION_CONTRACT_ADDRESS = activeNetwork.contracts.resolutionDAO

/**
 * Collateral token address (USDC on Base, IND on L3)
 */
export const COLLATERAL_TOKEN_ADDRESS = activeNetwork.collateralToken.address

/**
 * Collateral token symbol
 */
export const COLLATERAL_SYMBOL = activeNetwork.collateralToken.symbol

/**
 * Collateral token decimals
 */
export const COLLATERAL_DECIMALS = activeNetwork.collateralToken.decimals

/**
 * Minimum bet amount in collateral token base units
 * 0.01 tokens = 10^(decimals-2)
 */
export const MIN_BET_AMOUNT = BigInt(10 ** (COLLATERAL_DECIMALS - 2))

/**
 * Backend API URL
 * Empty string = same-origin (Vercel rewrites proxy to backend)
 */
export const BACKEND_URL = ''

// Legacy exports for backward compatibility
/** @deprecated Use CHAIN_ID instead */
export const BASE_CHAIN_ID = CHAIN_ID
/** @deprecated Use COLLATERAL_TOKEN_ADDRESS instead */
export const USDC_ADDRESS = COLLATERAL_TOKEN_ADDRESS
/** @deprecated Use COLLATERAL_DECIMALS instead */
export const USDC_DECIMALS = COLLATERAL_DECIMALS

/** @deprecated Use CONTRACT_ADDRESS directly */
export function getContractAddress(): `0x${string}` {
  return CONTRACT_ADDRESS
}

/** @deprecated Use RESOLUTION_CONTRACT_ADDRESS directly */
export function getResolutionContractAddress(): `0x${string}` {
  return RESOLUTION_CONTRACT_ADDRESS
}

/** @deprecated Use BACKEND_URL directly */
export function getBackendUrl(): string {
  return BACKEND_URL
}

/**
 * Get the active network configuration
 */
export function getActiveNetwork(): NetworkConfig {
  return activeNetwork
}

/**
 * Get all available networks
 */
export function getNetworks(): Record<string, NetworkConfig> {
  return networks
}

/**
 * Format amount for display based on collateral decimals
 */
export function formatCollateralAmount(amount: bigint | number): string {
  const value = typeof amount === 'bigint' ? Number(amount) : amount
  const displayValue = value / (10 ** COLLATERAL_DECIMALS)
  return displayValue.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: COLLATERAL_DECIMALS > 6 ? 4 : 2,
  })
}

/**
 * Parse display amount to base units
 */
export function parseCollateralAmount(displayAmount: number | string): bigint {
  const value = typeof displayAmount === 'string' ? parseFloat(displayAmount) : displayAmount
  return BigInt(Math.floor(value * (10 ** COLLATERAL_DECIMALS)))
}
