/**
 * Contract addresses for the AgiArena platform
 * AUTO-GENERATED by sync-addresses.sh from contracts/addresses.json
 * DO NOT EDIT MANUALLY
 *
 * Story 4-3: Migrated to bilateral custody architecture.
 * Legacy AgiArenaCore and ResolutionDAO contracts are deprecated.
 *
 * Supports multiple chains:
 * - Index L3 (Chain ID: 111222333) - WIND as collateral
 */

/**
 * Network configurations
 */
interface NetworkConfig {
  chainId: number
  chainName: string
  contracts: {
    // Bilateral custody contracts (active)
    botRegistry: `0x${string}`
    collateralVault: `0x${string}`
    keeperRegistry: `0x${string}`
    // Legacy contracts (deprecated - kept for historical reference)
    agiArenaCore: `0x${string}`
    resolutionDAO: `0x${string}`
  }
  collateralToken: {
    address: `0x${string}`
    symbol: string
    decimals: number
  }
  rpcUrl: string
}

const networks: Record<string, NetworkConfig> = {
  'index-l3': {
    chainId: 111222333,
    chainName: 'Index L3',
    contracts: {
      // Bilateral custody contracts (active - VPS2 deployed 2026-02-03)
      botRegistry: '0x9dF23e34ac13A7145ebA1164660E701839197B1b',
      collateralVault: '0x5F0053e7F8D70d14aa0Ec7590b99aa5f919dB607',
      keeperRegistry: '0xE80FB0E8974EFE237fEf83B0df470664fc51fa99',
      // Legacy contracts (deprecated)
      agiArenaCore: '0x873256196B70c5a7fC08A820089293302F492d08',
      resolutionDAO: '0x1B1157f2C4E8821B4172dDA17730E9807aceEe88',
    },
    collateralToken: {
      address: '0x6Ef9653b34C2A0d91219466b029428ff4F49D651',
      symbol: 'WIND',
      decimals: 18,
    },
    rpcUrl: 'https://index.rpc.zeeve.net',
  },
}

// Index Protocol Contracts (ITP creation and trading)
// Loaded from environment variables - auto-synced by sync-deployment.sh
export const INDEX_PROTOCOL = {
  bridgeProxy: (process.env.NEXT_PUBLIC_BRIDGE_PROXY_ADDRESS || '0xfBaBC11c9F238556880589b092fb199AF273849B') as `0x${string}`,
  bridgedItpFactory: (process.env.NEXT_PUBLIC_BRIDGED_ITP_FACTORY_ADDRESS || '0xf6aF8ae82FE5158f5008CAD1C0A70e69062cc0dc') as `0x${string}`,
  index: (process.env.NEXT_PUBLIC_INDEX_ADDRESS || '0xeD31026718e15Ffcff000831dD568a351354ADC2') as `0x${string}`,
  issuerRegistry: (process.env.NEXT_PUBLIC_ISSUER_REGISTRY_ADDRESS || '0xae3DcC43AC2E735C43b2a2bCd9C25FcA00441785') as `0x${string}`,
  assetPairRegistry: (process.env.NEXT_PUBLIC_ASSET_PAIR_REGISTRY_ADDRESS || '0x9705f5D06C229FAb0A284aBB12aA521eF7E8E070') as `0x${string}`,
  mockBitgetVault: (process.env.NEXT_PUBLIC_MOCK_BITGET_VAULT_ADDRESS || '0xf4cb5a411C07a8A346998Ed71e5A45f83E0A4Dfe') as `0x${string}`,
}

/**
 * Active network based on environment variable
 * Defaults to index-l3
 */
const activeNetworkKey = process.env.NEXT_PUBLIC_ACTIVE_NETWORK || 'index-l3'
const activeNetwork = networks[activeNetworkKey] || networks['index-l3']

/**
 * Chain ID for the active network
 */
export const CHAIN_ID = activeNetwork.chainId

/**
 * BotRegistry contract address (peer discovery)
 */
export const BOT_REGISTRY_ADDRESS = activeNetwork.contracts.botRegistry

/**
 * CollateralVault contract address (bilateral custody)
 */
export const COLLATERAL_VAULT_ADDRESS = activeNetwork.contracts.collateralVault

/**
 * KeeperRegistry contract address (arbitration)
 */
export const KEEPER_REGISTRY_ADDRESS = activeNetwork.contracts.keeperRegistry

/**
 * ReferralVault contract address (merkle-based referral rewards)
 * Story 7-1 — will be set after deployment
 */
export const REFERRAL_VAULT_ADDRESS = (process.env.NEXT_PUBLIC_REFERRAL_VAULT_ADDRESS || '0xFebF79624d74eEAb1Cde0655264801D46369d9a9') as `0x${string}`

/**
 * @deprecated Legacy AgiArenaCore contract address - use bilateral contracts instead
 */
export const CONTRACT_ADDRESS = activeNetwork.contracts.agiArenaCore

/**
 * @deprecated Legacy ResolutionDAO contract address - use bilateral contracts instead
 */
export const RESOLUTION_CONTRACT_ADDRESS = activeNetwork.contracts.resolutionDAO

/**
 * Collateral token address (USDC on Base, IND on L3)
 */
export const COLLATERAL_TOKEN_ADDRESS = activeNetwork.collateralToken.address

/**
 * Collateral token symbol
 */
export const COLLATERAL_SYMBOL = activeNetwork.collateralToken.symbol

/**
 * Collateral token decimals
 */
export const COLLATERAL_DECIMALS = activeNetwork.collateralToken.decimals

/**
 * Minimum bet amount in collateral token base units
 * 0.01 tokens = 10^(decimals-2)
 */
export const MIN_BET_AMOUNT = BigInt(10 ** (COLLATERAL_DECIMALS - 2))

/**
 * Backend API URL
 * Empty string = same-origin (Vercel rewrites proxy to backend)
 */
export const BACKEND_URL = ''

/** @deprecated Use BACKEND_URL directly - kept for backward compatibility (used in 17+ files) */
export function getBackendUrl(): string {
  return BACKEND_URL
}

/**
 * Get the active network configuration
 */
export function getActiveNetwork(): NetworkConfig {
  return activeNetwork
}

/**
 * Get all available networks
 */
export function getNetworks(): Record<string, NetworkConfig> {
  return networks
}

/**
 * Format amount for display based on collateral decimals
 */
export function formatCollateralAmount(amount: bigint | number): string {
  const value = typeof amount === 'bigint' ? Number(amount) : amount
  const displayValue = value / (10 ** COLLATERAL_DECIMALS)
  return displayValue.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: COLLATERAL_DECIMALS > 6 ? 4 : 2,
  })
}

/**
 * Parse display amount to base units
 */
export function parseCollateralAmount(displayAmount: number | string): bigint {
  const value = typeof displayAmount === 'string' ? parseFloat(displayAmount) : displayAmount
  return BigInt(Math.floor(value * (10 ** COLLATERAL_DECIMALS)))
}
